# Generated 2025-04-01 from:
# /data/anakuzne/speechbrain/recipes/UrbanSound8k/SoundClassification/ecapa_tdnn/hparams/hopt/hopt_ecapa_tdnnq.yaml
# yamllint disable
# #################################
# Basic training parameters for urban sound classification. We have first a network that
# computes some embeddings. On the top of that, we employ a classifier.
#
# Author:
#  * David Whipps 2021
#  * Ala Eddine Limame 2021
# #################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1988
__set_seed: !apply:speechbrain.utils.seed_everything [1988]

# Set up folders for reading from and writing to
# Dataset must already exist at `audio_data_folder`
data_folder: /data/anakuzne/datatsets/UrbanSound8K
                          # e.g., /localscratch/UrbanSound8K
data_folder_noise: /data/anakuzne/datatsets/UrbanSound8K/noise # The noisy sequences for data augmentation will automatically be downloaded here.
data_folder_rir: /data/anakuzne/datatsets/UrbanSound8K/rir # The impulse responses used for data augmentation will automatically be downloaded here.
audio_data_folder: /data/anakuzne/datatsets/UrbanSound8K/audio
# TODO the following folder will contain the resampled audio files (mono channel and config SR) to train on
# resampled_audio_data_folder: !ref <data_folder>/audio_mono16kHz
output_folder: debugq
save_folder: debugq/save
train_log: debugq/train_log.txt
cached_data_folder: cache/

pretrained_model_path: 
  /data/anakuzne/speechbrain/recipes/UrbanSound8k/SoundClassification/ecapa_tdnn/results/urban_sound_2x/save/CKPT+2025-04-01+13-43-48+00

# Data for augmentation
NOISE_DATASET_URL: 
  https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1
RIR_DATASET_URL: 
  https://www.dropbox.com/scl/fi/linhy77c36mu10965a836/RIRs.zip?rlkey=pg9cu8vrpn2u173vhiqyu743u&dl=1


# torch.Tensorboard logs
use_tensorboard: true
tensorboard_logs_folder: debugq/tb_logs/

# Path where data manifest files will be stored
train_annotation: debugq/save/manifest/train.json
valid_annotation: debugq/save/manifest/valid.json
test_annotation: debugq/save/manifest/test.json
noise_annotation: debugq/save/noise.csv
rir_annotation: debugq/save/rir.csv

# To standardize results, UrbanSound8k has pre-separated samples into
# 10 folds for multi-fold validation
train_fold_nums: [1, 2, 3, 4, 5, 6, 7, 8]
valid_fold_nums: [9]
test_fold_nums: [10]
skip_manifest_creation: false
testing: true

ckpt_interval_minutes: 15 # save checkpoint every N min

####################### Training Parameters ####################################
number_of_epochs: 25
batch_size_exponent: 4 # @orion_step1: --batch_size_exponent~"uniform(2, 4,discrete=True)"
batch_size: 16
lr: 0.001 # @orion_step1: --lr~"loguniform(0.00001,0.1)"
base_lr: 0.00000001
max_lr: 0.001
step_size: 65000
sample_rate: 16000

# RVQ parameters
n_codebooks: 1  # Number of codebooks for RVQ
vocab_size: 1024
codebook_dim_exponent: 2 # @orion_step1: --codebook_dim_exponent~"uniform(1, 3,discrete=True)"
merge_codes: true
last_channel_dim: 1536

quantize_layer_idx: 3
vq_loss_weight: 0.01 # @orion_step1: --vq_loss_weight~"loguniform(0.00001,0.1)"

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: false
amp_to_db: false
normalize: true

# Number of classes
out_n_neurons: 10

# Note that it's actually important to shuffle the data here
# (or at the very least, not sort the data by duration)
# Also note that this does not violate the UrbanSound8k "no-shuffle" policy
# because this does not mix samples from folds in train to valid/test, only
# within train or valid, or test
shuffle: true
num_workers: 4
dataloader_options:
  batch_size: 16
  shuffle: true
  num_workers: 4

# Functions
compute_features: &id007 !new:speechbrain.lobes.features.Fbank
  n_mels: 80
  left_frames: 0
  right_frames: 0
  deltas: false

embedding_model: &id008 !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNNQ
  input_size: 80
  channels: [1024, 1024, 1024, 1024, 1536]                       # Number of channels in each TDNN layer
  kernel_sizes: [5, 3, 3, 3, 1]
  dilations: [1, 2, 3, 4, 1]
  attention_channels: 128
  lin_neurons: 192
  num_codebooks: 1                     # Number of codebooks for RVQ
  codebook_size: 1024                 # Size of each codebook
  quantize_layer: 3                            # Layer index to apply RVQ
  codebook_dim: 64                                   # Dimensionality of the codebook vectors
  merge_codes: true                  # Whether to merge codebooks into a single representation

classifier: &id009 !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
  input_size: 192
  out_neurons: 10

epoch_counter: &id011 !new:speechbrain.utils.epoch_loop.EpochCounter

  limit: 25


# Download and prepare the dataset of noisy sequences for augmentation
prepare_noise_data: !name:speechbrain.augment.preparation.prepare_dataset_from_URL
  URL: 
    https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1
  dest_folder: /data/anakuzne/datatsets/UrbanSound8K/noise
  ext: wav
  csv_file: debugq/save/noise.csv

# Speed perturbation
speed_changes: &id001 [95, 100, 105]

# Add noise to input signal
speed_perturb: &id002 !new:speechbrain.augment.time_domain.SpeedPerturb
  orig_freq: 16000
  speeds: *id001
snr_low: 0  # Min SNR for noise augmentation
snr_high: 15  # Max SNR for noise augmentation

add_noise: &id003 !new:speechbrain.augment.time_domain.AddNoise
  csv_file: debugq/save/noise.csv
  snr_low: 0
  snr_high: 15
  noise_sample_rate: 16000
  clean_sample_rate: 16000
  num_workers: 4


# Download and prepare the dataset of room impulse responses for augmentation
prepare_rir_data: !name:speechbrain.augment.preparation.prepare_dataset_from_URL
  URL: 
    https://www.dropbox.com/scl/fi/linhy77c36mu10965a836/RIRs.zip?rlkey=pg9cu8vrpn2u173vhiqyu743u&dl=1
  dest_folder: /data/anakuzne/datatsets/UrbanSound8K/rir
  ext: wav
  csv_file: debugq/save/rir.csv

# Add reverberation to input signal
add_reverb: &id004 !new:speechbrain.augment.time_domain.AddReverb
  csv_file: debugq/save/rir.csv
  reverb_sample_rate: 16000
  clean_sample_rate: 16000
  num_workers: 4

# Frequency drop: randomly drops a number of frequency bands to zero.
drop_freq_low: 0  # Min frequency band dropout probability
drop_freq_high: 1  # Max frequency band dropout probability
drop_freq_count_low: 1  # Min number of frequency bands to drop
drop_freq_count_high: 3  # Max number of frequency bands to drop
drop_freq_width: 0.05  # Width of frequency bands to drop

drop_freq: &id005 !new:speechbrain.augment.time_domain.DropFreq
  drop_freq_low: 0
  drop_freq_high: 1
  drop_freq_count_low: 1
  drop_freq_count_high: 3
  drop_freq_width: 0.05

# Time drop: randomly drops a number of temporal chunks.
drop_chunk_count_low: 1  # Min number of audio chunks to drop
drop_chunk_count_high: 5  # Max number of audio chunks to drop
drop_chunk_length_low: 1000  # Min length of audio chunks to drop
drop_chunk_length_high: 2000  # Max length of audio chunks to drop

drop_chunk: &id006 !new:speechbrain.augment.time_domain.DropChunk
  drop_length_low: 1000
  drop_length_high: 2000
  drop_count_low: 1
  drop_count_high: 5

# Augmenter: Combines previously defined augmentations to perform data augmentation
wav_augment: !new:speechbrain.augment.augmenter.Augmenter
  parallel_augment: true
  concat_original: true
  repeat_augment: 1
  shuffle_augmentations: false
  min_augmentations: 4
  max_augmentations: 4
  augment_prob: 1.0
  augmentations: [*id002, *id003, *id004, *id005, *id006]

mean_var_norm: &id010 !new:speechbrain.processing.features.InputNormalization

  norm_type: sentence
  std_norm: false

modules:
  compute_features: *id007
  embedding_model: *id008
  classifier: *id009
  mean_var_norm: *id010
compute_cost: !new:speechbrain.nnet.losses.LogSoftmaxWrapper
  loss_fn: !new:speechbrain.nnet.losses.AdditiveAngularMargin
    margin: 0.2
    scale: 30

# compute_error: !name:speechbrain.nnet.losses.classification_error

opt_class: !name:torch.optim.Adam
  lr: 0.001
  weight_decay: 0.000002

lr_annealing: !new:speechbrain.nnet.schedulers.CyclicLRScheduler
  base_lr: 0.00000001
  max_lr: 0.001
  step_size: 65000

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: debugq/train_log.txt

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
  metric: !name:speechbrain.nnet.losses.classification_error
    reduction: batch

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: debugq/save
  recoverables:
    embedding_model: *id008
    classifier: *id009
    normalizer: *id010
    counter: *id011
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  collect_in: debugq/save
  loadables:
    embedding_model: *id008
    classifier: *id009
  paths:
    embedding_model: 
      /data/anakuzne/speechbrain/recipes/UrbanSound8k/SoundClassification/ecapa_tdnn/results/urban_sound_2x/save/CKPT+2025-04-01+13-43-48+00/embedding_model.ckpt
    classifier: 
      /data/anakuzne/speechbrain/recipes/UrbanSound8k/SoundClassification/ecapa_tdnn/results/urban_sound_2x/save/CKPT+2025-04-01+13-43-48+00/classifier.ckpt
