# Generated 2025-03-27 from:
# /data/anakuzne/speechbrain/recipes/LibriSpeech/ASR/transformer/hparams/debug.yaml
# yamllint disable
# ############################################################################
# Model: E2E ASR with Transformer
# Encoder: Conformer Encoder
# Decoder: Transformer Decoder + (CTC/ATT joint) beamsearch + TransformerLM
# losses: CTC + KLdiv (Label Smoothing loss)
# Training: Librispeech 960h
# Authors:  Jianyuan Zhong, Titouan Parcollet, Samuele Cornell
# ############################################################################
# Seed needs to be set at top of yaml, before objects with parameters are made

seed: 3407
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !PLACEHOLDER
output_wer_folder: !ref <output_folder>/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
cached_data_folder: !PLACEHOLDER

# Load the pretrained Conformer and LM from Huggingface
pretrained_model_path: !PLACEHOLDER
pretrained_lm_tokenizer_path: speechbrain/asr-transformer-transformerlm-librispeech

data_folder: !PLACEHOLDER
train_splits: [train-clean-100, train-clean-360, train-other-500]
dev_splits: [dev-clean]
test_splits: [dev-clean, test-clean, test-other]
skip_prep: false
train_csv: !ref <output_folder>/train.csv
valid_csv: !ref <output_folder>/dev-clean.csv
test_csv:
    - !ref <output_folder>/dev-clean.csv
    - !ref <output_folder>/test-clean.csv
    - !ref <output_folder>/test-other.csv
testing: true
####################### Training Parameters ####################################

# To make Transformers converge, the global bath size should be large enough.
# The global batch size is computed as batch_size * n_gpus * grad_accumulation_factor.
# Empirically, we found that this value should be >= 128.
# Please, set your parameters accordingly.
number_of_epochs: 20
batch_size_exponent: 2
batch_size: !ref 2 ** <batch_size_exponent>
ctc_weight: 0.3
seq_weight: 0.7
codec_loss_weight: 0.2
quantize_layer: 4
grad_accumulation_factor: 1
max_grad_norm: 5.0
loss_reduction: batchmean
sorting: random
num_workers: 4
precision: fp32 # bf16, fp16 or fp32
avg_checkpoints: 10 # Number of checkpoints to average for evaluation
codebook_dim_exponent: 2

# stages related parameters
lr_adam: 1.639e-05
warmup: 50000
augment_warmup: 8000

# Feature parameters
sample_rate: 16000
n_fft: 512
n_mels: 80
win_length: 32
n_codebooks: 1
vocab_size: 1024


# This setup works well for A100 80GB GPU, adapts it to your needs.
# Or turn it off (but training speed will decrease)
dynamic_batching: true
max_batch_length_train: 500
max_batch_length_val: 100 # we reduce it as the beam is much wider (VRAM)
num_bucket: 200
shuffle: true # if true re-creates batches at each epoch shuffling examples.
batch_ordering: random
max_batch_ex: 256

dynamic_batch_sampler_train:
  max_batch_length: 500
  num_buckets: 200
  shuffle: true
  batch_ordering: random
  max_batch_ex: 256

dynamic_batch_sampler_valid:
  max_batch_length: 100
  num_buckets: 200
  shuffle: true
  batch_ordering: random
  max_batch_ex: 256

# Dataloader options
train_dataloader_opts:
  batch_size: 16
  shuffle: true
  num_workers: 4

valid_dataloader_opts:
  batch_size: 1

test_dataloader_opts:
  batch_size: 1

####################### Model Parameters #######################################

# Transformer
d_model: 512
nhead: 8
num_encoder_layers: 12
num_decoder_layers: 6
d_ffn: 2048
transformer_dropout: 0.1
activation: &id001 !name:torch.nn.GELU
output_neurons: 5000

# Outputs
blank_index: 0
label_smoothing: 0.1
pad_index: 0
bos_index: 1
eos_index: 2

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
valid_search_interval: 1
valid_beam_size: 10
test_beam_size: 66
lm_weight: 0.60
ctc_weight_decode: 0.40

############################## Models ##########################################

Transformer: !new:speechbrain.lobes.models.transformer.TransformerASR.TransformerASR # yamllint disable-line rule:line-length
    input_size: 640
    tgt_vocab: !ref <output_neurons>
    d_model: !ref <d_model>
    nhead: !ref <nhead>
    num_encoder_layers: !ref <num_encoder_layers>
    num_decoder_layers: !ref <num_decoder_layers>
    d_ffn: !ref <d_ffn>
    dropout: !ref <transformer_dropout>
    activation: !ref <activation>
    encoder_module: conformerq
    attention_type: RelPosMHAXL
    normalize_before: True
    causal: False
    freeze_encoder: False
    freeze_decoder: False
    num_codebooks: !ref <n_codebooks>
    codebook_size: !ref <vocab_size>
    codebook_dim: !ref 8 ** <codebook_dim_exponent>
    quantize_layer: !ref <quantize_layer>


# This is the TransformerLM that is used according to the Huggingface repository
# Visit the HuggingFace model corresponding to the pretrained_lm_tokenizer_path
# For more details about the model!
# NB: It has to match the pre-trained TransformerLM!!
lm_model: &id007 !new:speechbrain.lobes.models.transformer.TransformerLM.TransformerLM
                                                                                # yamllint disable-line rule:line-length
  vocab: 5000
  d_model: 768
  nhead: 12
  num_encoder_layers: 12
  num_decoder_layers: 0
  d_ffn: 3072
  dropout: 0.0
  activation: !name:torch.nn.GELU
  normalize_before: false

tokenizer: &id018 !new:sentencepiece.SentencePieceProcessor

ctc_lin: &id005 !new:speechbrain.nnet.linear.Linear


  input_size: 512
  n_neurons: 5000

seq_lin: &id004 !new:speechbrain.nnet.linear.Linear
  input_size: 512
  n_neurons: 5000

normalize: &id006 !new:speechbrain.processing.features.InputNormalization

# define two optimizers here for two-stage training
  norm_type: global
  update_until_epoch: 4

modules:
  CNN: *id002
  Transformer: *id003
  seq_lin: *id004
  ctc_lin: *id005
  normalize: *id006
Adam: !name:torch.optim.AdamW
  lr: 0.0008
  betas: (0.9, 0.98)
  eps: 0.000000001

model: &id012 !new:torch.nn.ModuleList
- [*id002, *id003, *id004, *id005]
ctc_scorer: &id009 !new:speechbrain.decoders.scorer.CTCScorer
  eos_index: 2
  blank_index: 0
  ctc_fc: *id005
transformerlm_scorer: &id008 !new:speechbrain.decoders.scorer.TransformerLMScorer
  language_model: *id007
  temperature: 1.15

scorer_test_search: &id011 !new:speechbrain.decoders.scorer.ScorerBuilder

  full_scorers: [*id008, *id009]
  weights:
    ctc: 0.40
    transformerlm: 0.60

scorer_valid_search: &id010 !new:speechbrain.decoders.scorer.ScorerBuilder

  full_scorers: [*id009]
  weights:
    ctc: 0.40

valid_search: !new:speechbrain.decoders.S2STransformerBeamSearcher
  modules: [*id003, *id004]
  bos_index: 1
  eos_index: 2
  min_decode_ratio: 0.0
  max_decode_ratio: 1.0
  beam_size: 10
  using_eos_threshold: false
  length_normalization: true
  scorer: *id010
test_search: !new:speechbrain.decoders.S2STransformerBeamSearcher
  modules: [*id003, *id004]
  bos_index: 1
  eos_index: 2
  min_decode_ratio: 0.0
  max_decode_ratio: 1.0
  beam_size: 66
  temperature: 1.15
  using_eos_threshold: false
  length_normalization: true
  scorer: *id011
log_softmax: !new:torch.nn.LogSoftmax
  dim: -1

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
  blank_index: 0
  reduction: batchmean

seq_cost: !name:speechbrain.nnet.losses.kldiv_loss
  label_smoothing: 0.1
  reduction: batchmean

noam_annealing: &id013 !new:speechbrain.nnet.schedulers.NoamScheduler
  lr_initial: 0.0008
  n_warmup_steps: 30000

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: results/develop-conformer-250bps/save
  recoverables:
    model: *id012
    noam_scheduler: *id013
    normalizer: *id006
    counter: &id014 !new:speechbrain.utils.epoch_loop.EpochCounter

      limit: 20

############################## Augmentations ###################################

# Speed perturbation
epoch_counter: *id014
speed_perturb: !new:speechbrain.augment.time_domain.SpeedPerturb
  orig_freq: 16000
  speeds: [95, 100, 105]

# Time Drop
time_drop: &id015 !new:speechbrain.augment.freq_domain.SpectrogramDrop
  drop_length_low: 15
  drop_length_high: 25
  drop_count_low: 4
  drop_count_high: 4
  replace: mean

# Freq Drop
freq_drop: &id016 !new:speechbrain.augment.freq_domain.SpectrogramDrop
  drop_length_low: 10
  drop_length_high: 20
  drop_count_low: 4
  drop_count_high: 4
  replace: mean
  dim: 2

# Time warp
time_warp: &id017 !new:speechbrain.augment.freq_domain.Warping

fea_augment: !new:speechbrain.augment.augmenter.Augmenter
  min_augmentations: 3
  max_augmentations: 3
  augment_prob: 1.0
  augmentations: [*id015, *id016, *id017]

compute_features: !new:speechbrain.lobes.features.Fbank
  sample_rate: 16000
  n_fft: 512
  n_mels: 80
  win_length: 32

############################## Logging and Pretrainer ##########################

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: results/develop-conformer-250bps/train_log.txt

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
  split_tokens: true
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
acc_computer: !name:speechbrain.utils.Accuracy.AccuracyStats

# The pretrainer allows a mapping between pretrained files and instances that
# are declared in the yaml. E.g here, we will download the file lm.ckpt
# and it will be loaded into "lm" which is pointing to the <lm_model> defined
# before.
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  collect_in: results/develop-conformer-250bps/save
  loadables:
    lm: *id007
    tokenizer: *id018
    model: *id012
  paths:
    lm: speechbrain/asr-transformer-transformerlm-librispeech/lm.ckpt
    tokenizer: speechbrain/asr-transformer-transformerlm-librispeech/tokenizer.ckpt
    model: <pretrained_model_path>/model.ckpt
eval_only: false
