# ################################
# Recipe for training then testing speaker embeddings using the VoxCeleb1 Dataset.
# Embeddings are used using the ECAPA-TDNN network
#
# Authors
# * Pooneh Mousavi 2024
# ################################

# Basic parameters
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/VoxCeleb1/dac/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
# Data files
data_folder: /storage/anakuzne/dataset/voxceleb/voxceleb1/  # e.g. /path/to/Voxceleb
train_annotation: !ref <save_folder>/train.csv
valid_annotation: !ref <save_folder>/dev.csv

verification_file: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt #path/to/veri_test2.txt

train_data: !ref <save_folder>/train.csv
enrol_data: !ref <save_folder>/enrol.csv
test_data: !ref <save_folder>/test.csv
dev_data: !ref  <save_folder>/dev.csv

verif_batch_size: 2
n_train_snts: 300000 # used for normalization stats

# Dataloader options
dynamic_batch_sampler_train:
  max_batch_length: 500
  num_buckets: 200
  shuffle: true
  batch_ordering: random
  max_batch_ex: 256

dynamic_batch_sampler_valid:
  max_batch_length: 100
  num_buckets: 200
  shuffle: true
  batch_ordering: random
  max_batch_ex: 256

train_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True
    num_workers: 4
    drop_last: True

enrol_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

skip_prep: False
ckpt_interval_minutes: 15 # save checkpoint every N min
pretrain: True
do_verification: True

# Training parameters
precision: fp32
number_of_epochs: 15
batch_size: 8
lr: 0.001
base_lr: 0.00000001
max_lr: !ref <lr>
step_size: 65000
mask_length: 10
mask_prob: 0.65
lr_weights: 0.01
original_sample_rate: 16000
shuffle: True
random_chunk: True
sentence_len: 3


# Mel spectrogram parameters
sample_rate: 16000
n_fft: 512
n_mels: 80
win_length: 32
n_codebooks: 12
vocab_size: 1024
codebook_dim_exponent: 1 # @orion_step1: --codebook_dim_exponent~"uniform(1, 3,discrete=True)"
quantize_layer_idx: 10


# Feature parameters
encoder_dim: 512
# If set to True, the encoder_dim should be set to the dim of the tokenizer. For encodec it is 128.
init_embedding: False
freeze_embedding: True

# Number of speakers
out_n_neurons: 1211  #1211 for vox1  # 5994 for vox2, 7205 for vox1+vox2]

# Transformer params
d_model: 512
nhead: 8
num_encoder_layers: 12
num_decoder_layers: 6
d_ffn: 2048
transformer_dropout: 0.1
activation: !name:torch.nn.GELU

# Outputs
blank_index: 0
label_smoothing: 0.1
pad_index: 0
bos_index: 1
eos_index: 2

# Compute features
normalize: !new:speechbrain.processing.features.InputNormalization
# Speed perturbation
speed_perturb: !new:speechbrain.augment.time_domain.SpeedPerturb
  orig_freq: 16000
  speeds: [95, 100, 105]

# Time Drop
time_drop: !new:speechbrain.augment.freq_domain.SpectrogramDrop
  drop_length_low: 15
  drop_length_high: 25
  drop_count_low: 4
  drop_count_high: 4
  replace: mean

# Freq Drop
freq_drop: !new:speechbrain.augment.freq_domain.SpectrogramDrop
  drop_length_low: 10
  drop_length_high: 20
  drop_count_low: 4
  drop_count_high: 4
  replace: mean
  dim: 2
# Time warp
time_warp: !new:speechbrain.augment.freq_domain.Warping

fea_augment: !new:speechbrain.augment.augmenter.Augmenter
  min_augmentations: 3
  max_augmentations: 3
  augment_prob: 1.0
  augmentations: [!ref <time_drop>, !ref <freq_drop>, !ref <time_warp>]

compute_features: !new:speechbrain.lobes.features.Fbank
  sample_rate: 16000
  n_fft: 512
  n_mels: 80
  win_length: 32

# Modules
# CNN frontend
CNN: !new:speechbrain.lobes.models.convolution.ConvolutionFrontEnd
  input_shape: (8, 10, 80)
  num_blocks: 2
  num_layers_per_block: 1
  out_channels: (64, 32)
  kernel_sizes: (3, 3)
  strides: (2, 2)
  residuals: (False, False)

Transformer: !new:speechbrain.lobes.models.transformer.TransformerASR.TransformerASR                                                                                 # yamllint disable-line rule:line-length
  input_size: 640
  tgt_vocab: 5000
  d_model: 512
  nhead: 8
  num_encoder_layers: 12
  num_decoder_layers: 6
  d_ffn: 2048
  dropout: 0.1
  activation: !ref <activation>
  encoder_module: conformerq
  mode: quantize
  attention_type: RelPosMHAXL
  normalize_before: true
  causal: false
  freeze_encoder: false
  freeze_decoder: false
  num_codebooks: 12
  codebook_size: 1024
  codebook_dim: 8
  quantize_layer: 10

discrete_embedding_layer: !new:custom_model.Discrete_EmbeddingLayer
    num_codebooks: !ref <n_codebooks>
    vocab_size: !ref <vocab_size>
    emb_dim: !ref <encoder_dim>
    freeze: !ref <freeze_embedding>
    init: !ref <init_embedding>

attention_mlp: !new:custom_model.AttentionMLP
    input_dim: !ref <encoder_dim>
    hidden_dim: !ref <encoder_dim>

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <encoder_dim>
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    groups: [1, 1, 1, 1, 1]
    attention_channels: 128
    lin_neurons: 192

classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: 512
    out_neurons: !ref <out_n_neurons>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>


modules:
    CNN: !ref <CNN>
    Transformer: !ref <Transformer>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>
    attention_mlp: !ref <attention_mlp>
    discrete_embedding_layer: !ref <discrete_embedding_layer>
    normalize: !ref <normalize>

model: !new:torch.nn.ModuleList
    - [!ref <CNN>, !ref <Transformer>, !ref <embedding_model>, !ref <classifier>, !ref <discrete_embedding_layer>, !ref <attention_mlp>]

# Cost + optimization
compute_error: !name:speechbrain.nnet.losses.classification_error

compute_cost: !new:speechbrain.nnet.losses.LogSoftmaxWrapper
    loss_fn: !new:speechbrain.nnet.losses.AdditiveAngularMargin
        margin: 0.2
        scale: 30


model_opt_class: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0.000002

lr_annealing: !new:speechbrain.nnet.schedulers.CyclicLRScheduler
    base_lr: !ref <base_lr>
    max_lr: !ref <max_lr>
    step_size: !ref <step_size>

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        scheduler_model: !ref <lr_annealing>
        attention_mlp: !ref <attention_mlp>
        cnn: !ref <CNN>
        transformer: !ref <Transformer>
        discrete_embedding_layer: !ref <discrete_embedding_layer>
        classifier: !ref <classifier>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

mean_var_norm_emb: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

# The pretrainer allows a mapping between pretrained files and instances that
# are declared in the yaml. E.g here, we will download the file lm.ckpt
# and it will be loaded into "lm" which is pointing to the <lm_model> defined
# before.
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  collect_in: 
    #/storage/anakuzne/ckpt/conformer-large-3kbps-ql11/3407/save
    /storage/anakuzne/ckpt/conformer-large-3kbps-ql11/3407/save/CKPT+2025-05-06+13-26-13+00
  loadables:
    model: !ref <model>
  paths:
    model: 
      #/storage/anakuzne/ckpt/conformer-large-3kbps-ql11/3407/save/model.ckpt
      /storage/anakuzne/ckpt/conformer-large-3kbps-ql11/3407/save/CKPT+2025-05-06+13-26-13+00/model.ckpt
